//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the application you wish to block.
        /// </summary>
        public static string AppBlock {
            get {
                return ResourceManager.GetString("AppBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your choice:.
        /// </summary>
        public static string AskChoice {
            get {
                return ResourceManager.GetString("AskChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your Crypto Key.
        /// </summary>
        public static string CryptoKey {
            get {
                return ResourceManager.GetString("CryptoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your new path for the CryptoSoft.
        /// </summary>
        public static string CryptoSoftPath {
            get {
                return ResourceManager.GetString("CryptoSoftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Setting.
        /// </summary>
        public static string CurrentSetting {
            get {
                return ResourceManager.GetString("CurrentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID not found..
        /// </summary>
        public static string ErrorIdNotFound {
            get {
                return ResourceManager.GetString("ErrorIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the extensions you want to crypt.
        /// </summary>
        public static string ExtensionCryptAdd {
            get {
                return ResourceManager.GetString("ExtensionCryptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the extensions you want to crypt.
        /// </summary>
        public static string ExtensionCryptRemove {
            get {
                return ResourceManager.GetString("ExtensionCryptRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à invalid input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Blocked :.
        /// </summary>
        public static string ListApplicationSoftware {
            get {
                return ResourceManager.GetString("ListApplicationSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crypt Key : .
        /// </summary>
        public static string ListcryptoKey {
            get {
                return ResourceManager.GetString("ListcryptoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft Path : .
        /// </summary>
        public static string ListCryptoSoftPath {
            get {
                return ResourceManager.GetString("ListCryptoSoftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No jobs registered yet..
        /// </summary>
        public static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension Crypt : .
        /// </summary>
        public static string ListExtensionsToEncrypt {
            get {
                return ResourceManager.GetString("ListExtensionsToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID | Name | Type | Source -&gt; Destination.
        /// </summary>
        public static string ListHeader {
            get {
                return ResourceManager.GetString("ListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LogType : .
        /// </summary>
        public static string ListLogType {
            get {
                return ResourceManager.GetString("ListLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In what format would you like your daily reports to be presented ? (XML or Json).
        /// </summary>
        public static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EASYSAVE - MAIN MENU.
        /// </summary>
        public static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7. Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Create backup job.
        /// </summary>
        public static string MenuOption1 {
            get {
                return ResourceManager.GetString("MenuOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Modify backup job.
        /// </summary>
        public static string MenuOption2 {
            get {
                return ResourceManager.GetString("MenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Delete backup job.
        /// </summary>
        public static string MenuOption3 {
            get {
                return ResourceManager.GetString("MenuOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. List backup jobs.
        /// </summary>
        public static string MenuOption4 {
            get {
                return ResourceManager.GetString("MenuOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5. Execute backup job.
        /// </summary>
        public static string MenuOption5 {
            get {
                return ResourceManager.GetString("MenuOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6. Settings.
        /// </summary>
        public static string MenuOption6 {
            get {
                return ResourceManager.GetString("MenuOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave - Main Menu.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Up/Down arrows to navigate and Enter to confirm..
        /// </summary>
        public static string NavigationHelp {
            get {
                return ResourceManager.GetString("NavigationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to return to the menu....
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID of the job to delete:.
        /// </summary>
        public static string PromptDeleteId {
            get {
                return ResourceManager.GetString("PromptDeleteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination path (e.g., D:\Folder):.
        /// </summary>
        public static string PromptDest {
            get {
                return ResourceManager.GetString("PromptDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the ID of the job to execute (all pour tout exécuter) :.
        /// </summary>
        public static string PromptExecuteId {
            get {
                return ResourceManager.GetString("PromptExecuteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name:.
        /// </summary>
        public static string PromptJobName {
            get {
                return ResourceManager.GetString("PromptJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID of the job to modify:.
        /// </summary>
        public static string PromptModifyId {
            get {
                return ResourceManager.GetString("PromptModifyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New destination [{0}]:.
        /// </summary>
        public static string PromptNewDest {
            get {
                return ResourceManager.GetString("PromptNewDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New name [{0}]:.
        /// </summary>
        public static string PromptNewName {
            get {
                return ResourceManager.GetString("PromptNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New source [{0}]:.
        /// </summary>
        public static string PromptNewSource {
            get {
                return ResourceManager.GetString("PromptNewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New type [Current: {0}]:.
        /// </summary>
        public static string PromptNewType {
            get {
                return ResourceManager.GetString("PromptNewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source path (e.g., C:\Folder):.
        /// </summary>
        public static string PromptSource {
            get {
                return ResourceManager.GetString("PromptSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose backup type:.
        /// </summary>
        public static string PromptType {
            get {
                return ResourceManager.GetString("PromptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave setting menu.
        /// </summary>
        public static string SettingMenuExit {
            get {
                return ResourceManager.GetString("SettingMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingMenuTitle {
            get {
                return ResourceManager.GetString("SettingMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path of CryptoSoft.
        /// </summary>
        public static string SettingOption1 {
            get {
                return ResourceManager.GetString("SettingOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crypto Key.
        /// </summary>
        public static string SettingOption2 {
            get {
                return ResourceManager.GetString("SettingOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add extensions to encrypt.
        /// </summary>
        public static string SettingOption3 {
            get {
                return ResourceManager.GetString("SettingOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove extensions to encrypt.
        /// </summary>
        public static string SettingOption4 {
            get {
                return ResourceManager.GetString("SettingOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of log (Json or XML).
        /// </summary>
        public static string SettingOption5 {
            get {
                return ResourceManager.GetString("SettingOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application blocked.
        /// </summary>
        public static string SettingOption6 {
            get {
                return ResourceManager.GetString("SettingOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CREATE A NEW BACKUP JOB.
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BACKUP JOBS LIST.
        /// </summary>
        public static string TitleList {
            get {
                return ResourceManager.GetString("TitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifying: {0} (Leave empty to keep current value).
        /// </summary>
        public static string TitleModify {
            get {
                return ResourceManager.GetString("TitleModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential Backup.
        /// </summary>
        public static string TypeDiff {
            get {
                return ResourceManager.GetString("TypeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full Backup.
        /// </summary>
        public static string TypeFull {
            get {
                return ResourceManager.GetString("TypeFull", resourceCulture);
            }
        }
    }
}
